/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Model.Person;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author jacksonalexander
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJpanel
     */
    Person person;
    public ViewJPanel(Person person) {
        initComponents();
        this.person = person;
        displayProduct(); 
        displayPhoto();
        displayBiometric();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeoDate = new javax.swing.JLabel();
        lbldateOfbirth = new javax.swing.JLabel();
        lblTelephoneNum = new javax.swing.JLabel();
        lblFAXNum = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblSSN = new javax.swing.JLabel();
        lblmedRecnum = new javax.swing.JLabel();
        lblhealthPlanBenenum = new javax.swing.JLabel();
        lblbankAccnum = new javax.swing.JLabel();
        lblcertNum = new javax.swing.JLabel();
        lblvehIden = new javax.swing.JLabel();
        lbldeviceIden = new javax.swing.JLabel();
        lbllinkedIn = new javax.swing.JLabel();
        lblinternetProtocolAddress = new javax.swing.JLabel();
        lbluniqueIdentifyingNum = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtTelephoneNumber = new javax.swing.JTextField();
        txtFAXNumber = new javax.swing.JTextField();
        txtEmailAddresses = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        txtMedicalRecordNumber = new javax.swing.JTextField();
        txtHealthPlanBeneficiaryNum = new javax.swing.JTextField();
        txtCity = new javax.swing.JTextField();
        txtStreet = new javax.swing.JTextField();
        txtbankAccnum = new javax.swing.JTextField();
        txtcertNum = new javax.swing.JTextField();
        txtvehIden = new javax.swing.JTextField();
        txtdeviceIden = new javax.swing.JTextField();
        txtlinkedIn = new javax.swing.JTextField();
        txtinternetProtocolAddress = new javax.swing.JTextField();
        txtuniqueIdentifyingNum = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        lblBiometric = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View Profile");

        lblName.setText("Name:");

        lblGeoDate.setText("Geographic Data:");

        lbldateOfbirth.setText("Date of  Birth:");

        lblTelephoneNum.setText("Telephone Number:");

        lblFAXNum.setText("FAX Number:");

        lblEmail.setText("Email addresses:");

        lblSSN.setText("Social Security number:");

        lblmedRecnum.setText("Medical Record number:");

        lblhealthPlanBenenum.setText("Health plan beneficiary number:");

        lblbankAccnum.setText("Bank account numbers:");

        lblcertNum.setText("Certificate/license number:");

        lblvehIden.setText("Vehicle serial numbers:");

        lbldeviceIden.setText("Device identifiers and serial numbers:");

        lbllinkedIn.setText("LinkedIn:");

        lblinternetProtocolAddress.setText("Internet protocol addresses:");

        lbluniqueIdentifyingNum.setText("unique identifying number:");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCountryActionPerformed(evt);
            }
        });

        txtTelephoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelephoneNumberActionPerformed(evt);
            }
        });

        txtFAXNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAXNumberActionPerformed(evt);
            }
        });

        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblPhoto.setText("         Photo");

        lblBiometric.setText("Biometric");

        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblhealthPlanBenenum)
                                    .addComponent(lblmedRecnum)
                                    .addComponent(lblSSN)
                                    .addComponent(lblEmail)
                                    .addComponent(lblFAXNum)
                                    .addComponent(lblTelephoneNum)
                                    .addComponent(lbldateOfbirth)
                                    .addComponent(lblName)
                                    .addComponent(lblGeoDate)
                                    .addComponent(lblbankAccnum)
                                    .addComponent(lblcertNum)
                                    .addComponent(lblvehIden)
                                    .addComponent(lbldeviceIden)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblinternetProtocolAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbllinkedIn, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbluniqueIdentifyingNum, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStreet, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))
                            .addComponent(txtName)
                            .addComponent(txtHealthPlanBeneficiaryNum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMedicalRecordNumber)
                            .addComponent(txtSSN)
                            .addComponent(txtEmailAddresses)
                            .addComponent(txtFAXNumber)
                            .addComponent(txtTelephoneNumber)
                            .addComponent(txtbankAccnum)
                            .addComponent(txtcertNum)
                            .addComponent(txtvehIden)
                            .addComponent(txtdeviceIden)
                            .addComponent(txtlinkedIn)
                            .addComponent(txtinternetProtocolAddress)
                            .addComponent(txtuniqueIdentifyingNum)
                            .addComponent(txtDOB))
                        .addGap(0, 123, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(109, 109, 109))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28)
                        .addComponent(lblBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoto, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBiometric, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGeoDate)
                    .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldateOfbirth)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelephoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelephoneNum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFAXNum)
                    .addComponent(txtFAXNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmailAddresses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmedRecnum)
                    .addComponent(txtMedicalRecordNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhealthPlanBenenum)
                    .addComponent(txtHealthPlanBeneficiaryNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbankAccnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblbankAccnum, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcertNum)
                    .addComponent(txtcertNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblvehIden)
                    .addComponent(txtvehIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldeviceIden)
                    .addComponent(txtdeviceIden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllinkedIn)
                    .addComponent(txtlinkedIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblinternetProtocolAddress)
                    .addComponent(txtinternetProtocolAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbluniqueIdentifyingNum)
                    .addComponent(txtuniqueIdentifyingNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCountryActionPerformed

    private void txtTelephoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelephoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelephoneNumberActionPerformed

    private void txtFAXNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAXNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAXNumberActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBiometric;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFAXNum;
    private javax.swing.JLabel lblGeoDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSSN;
    private javax.swing.JLabel lblTelephoneNum;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblbankAccnum;
    private javax.swing.JLabel lblcertNum;
    private javax.swing.JLabel lbldateOfbirth;
    private javax.swing.JLabel lbldeviceIden;
    private javax.swing.JLabel lblhealthPlanBenenum;
    private javax.swing.JLabel lblinternetProtocolAddress;
    private javax.swing.JLabel lbllinkedIn;
    private javax.swing.JLabel lblmedRecnum;
    private javax.swing.JLabel lbluniqueIdentifyingNum;
    private javax.swing.JLabel lblvehIden;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JTextField txtEmailAddresses;
    private javax.swing.JTextField txtFAXNumber;
    private javax.swing.JTextField txtHealthPlanBeneficiaryNum;
    private javax.swing.JTextField txtMedicalRecordNumber;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtStreet;
    private javax.swing.JTextField txtTelephoneNumber;
    private javax.swing.JTextField txtbankAccnum;
    private javax.swing.JTextField txtcertNum;
    private javax.swing.JTextField txtdeviceIden;
    private javax.swing.JTextField txtinternetProtocolAddress;
    private javax.swing.JTextField txtlinkedIn;
    private javax.swing.JTextField txtuniqueIdentifyingNum;
    private javax.swing.JTextField txtvehIden;
    // End of variables declaration//GEN-END:variables

    private void displayProduct() {
        
        if(person.getDateOfbirth() == null) {
            
        }
        else {
            
        
         String dob = person.getDateOfbirth() +"";
         txtDOB.setText(dob);
        }
           txtName.setText(person.getName());
           txtCountry.setText(person.getCountry());
           txtCity.setText(person.getCity());
           txtStreet.setText(person.getStreet());
        //   jDateDOB.setText(person.getDateOfbirth());
           txtTelephoneNumber.setText(person.getTelePhone());
           txtFAXNumber.setText(person.getFaxNumber());
           txtEmailAddresses.setText(person.getEmailId());
           if(person.getSsn()==0){
               
           }
           else{
               txtSSN.setText(Long.toString(person.getSsn()));
           }
           
           txtMedicalRecordNumber.setText(person.getMedRecnum())  ;    
           txtHealthPlanBeneficiaryNum.setText(person.getHealthPlanBenenum());
           txtbankAccnum.setText(person.getBankAccnum());
           txtcertNum.setText(person.getCertNum());
           txtvehIden.setText(person.getVehIden());
           txtdeviceIden.setText(person.getDeviceIden());
           txtlinkedIn.setText(person.getLinkedIn());
           txtinternetProtocolAddress.setText(person.getInternetProtocolAddress());
           txtuniqueIdentifyingNum.setText(person.getUniqueIdentifyingNum()); 
           
                 
    }
    private void displayPhoto(){
        System.out.println(person.getPhoto());
        ImageIcon imageIconA = new javax.swing.ImageIcon(person.getPhoto());
        Image image1 = imageIconA.getImage(); // transform it
        Image newimg1 = image1.getScaledInstance(150, 150,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIconA = new ImageIcon(newimg1);
         lblPhoto.setIcon(imageIconA);
//         lblPhoto.setText("");
          
        
    }
    private void displayBiometric(){
                System.out.println(person.getBiometric());
        ImageIcon imageIcon = new javax.swing.ImageIcon(person.getBiometric());
        Image image1 = imageIcon.getImage(); // transform it
        Image newimg1 = image1.getScaledInstance(150, 150,  java.awt.Image.SCALE_SMOOTH); // scale it the smooth way
        imageIcon = new ImageIcon(newimg1);
        lblBiometric.setIcon(imageIcon);
//        lblBiometric.setText("");
          
        
    }
}
