/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import models.City;
import models.Community;
import models.Patient;
import models.PatientDirectory;
import models.PersonDirectory;
import models.Person;

/**
 *
 * @author jacksonalexander
 */
public class PatientCreateJPanel extends javax.swing.JPanel {

    
    PersonDirectory listOfPerson;
    PatientDirectory listOfPatient;
    City city;
    Person p;
    Patient Pa;
    Community community;
    ArrayList<City> listOfCity;
    /**
     * Creates new form PersonCreate
     */

    public PatientCreateJPanel(PersonDirectory listOfPerson,PatientDirectory listOfPatient) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
    this.listOfPatient=listOfPatient;
   this.listOfPerson = listOfPerson;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtInsertDisease = new javax.swing.JTextField();
        txtInsertssn = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblInsertaddress = new javax.swing.JLabel();
        lblInsertssn = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(143, 188, 219));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("                                                         Insert Patient Detail");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel7.setText("Address Should be alphanumericals");

        txtInsertDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertDiseaseActionPerformed(evt);
            }
        });

        txtInsertssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertssnActionPerformed(evt);
            }
        });

        btnInsert.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel5.setText("SSN should be of 9 Digits");

        lblInsertaddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertaddress.setText("Disease:");

        lblInsertssn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertssn.setText("SSN:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertssn)
                    .addComponent(lblInsertaddress))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtInsertssn, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtInsertDisease, txtInsertssn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertssn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertssn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtInsertDisease, txtInsertssn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsertDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertDiseaseActionPerformed

    private void txtInsertssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertssnActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        int flag_count = 0;
       
     
        long ssn=0;
        int i;
        
        
        String name = "";
        int age = 0;
        String sex = "";
        String address = "";
        long phoneNumber = 0;
        String disease="";
        System.out.println("check11 " + this.listOfPerson.getListOfPerson().size());
        for(i=0; i<this.listOfPerson.getListOfPerson().size(); i++) {
            System.out.println("check12 "+txtInsertssn.getText() + " " + Long.toString(this.listOfPerson.getListOfPerson().get(i).getSsn()));
        if(txtInsertssn.getText().equals(Long.toString(this.listOfPerson.getListOfPerson().get(i).getSsn()))){
        flag_count =1;
        System.out.println("check10");
        break;
        } }
        int flag_count1 = 1;
        if(flag_count ==1){
        name= this.listOfPerson.getListOfPerson().get(i).getName();
            age=this.listOfPerson.getListOfPerson().get(i).getAge();
            sex=this.listOfPerson.getListOfPerson().get(i).getSex();
            address=this.listOfPerson.getListOfPerson().get(i).getAddress();
            phoneNumber=this.listOfPerson.getListOfPerson().get(i).getPhoneNumber();
            ssn=this.listOfPerson.getListOfPerson().get(i).getSsn();
                    
        
        if(txtInsertDisease.getText().length()==0)
        {System.out.println("check6 "+txtInsertDisease.getText());
            flag_count1=0;
        } else if(Pattern.matches("[a-zA-Z]+\\.?",txtInsertDisease.getText()))
        {
            disease=txtInsertDisease.getText(); 
            System.out.println("check6 "+txtInsertDisease.getText());
            Patient patient ;
            try {
                patient = new Patient(name, ssn, address, age, sex, phoneNumber,disease);
                        this.listOfPatient.addNewPatient(patient);

            } catch (IOException ex) {
                Logger.getLogger(PatientCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ParseException ex) {
                Logger.getLogger(PatientCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (BadLocationException ex) {
                Logger.getLogger(PatientCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
                        JOptionPane.showMessageDialog(this, "Patient Information Saved.");

            // Prints disease
        }else{System.out.println("This is an invalid Input");
            flag_count1=0;
        }
        } 
        else {
                    JOptionPane.showMessageDialog(this, "Invalid SSN");

        }
       
      
//       if(flag_count1==1){
//            JOptionPane.showMessageDialog(this, "Patient Information Saved.");
//        
//        Patient patient ;
//            try {
//                patient = new Patient(name, ssn, address, age, sex, phoneNumber,disease);
//                        this.listOfPatient.addNewPatient(patient);
//
//            } catch (IOException ex) {
//                Logger.getLogger(PatientCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (ParseException ex) {
//                Logger.getLogger(PatientCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
//            } catch (BadLocationException ex) {
//                Logger.getLogger(PatientCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
//            }
//        }
//       else if(flag_count1==1 &&flag_count ==1 ){
//        JOptionPane.showMessageDialog(this, "Invalid SSN");
//       }
//    else{
//            JOptionPane.showMessageDialog(this, "Invalid SSN");
//     }
       
//        Person person = new Person(name,ssn,address, age,sex,phoneNumber);
      
        //        populatePersonTable(this.listOfPerson.getListOfPerson());
    }//GEN-LAST:event_btnInsertActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInsertaddress;
    private javax.swing.JLabel lblInsertssn;
    private javax.swing.JTextField txtInsertDisease;
    private javax.swing.JTextField txtInsertssn;
    // End of variables declaration//GEN-END:variables

    private void populatePersonTable(ArrayList<Person> listOfPerson) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
