/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import models.Person;
import models.PersonDirectory;
import java.awt.Image;
import java.io.IOException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.BadLocationException;
import models.Encounter;
import models.EncounterHistory;
import models.Patient;
import models.PatientDirectory;

/**
 *
 * @author jacksonalexander
 */
public class PatientModifyViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJpanel
     */
    Patient patient;
    Encounter e;
    PatientDirectory listOfPatient;
    EncounterHistory encounterHistory;
    
    public PatientModifyViewJPanel(PatientDirectory listOfPatient,EncounterHistory encounterHistory) {
        initComponents();
        this.listOfPatient = listOfPatient;
        this.encounterHistory = encounterHistory;
   
        
        populateEncounterTable(this.encounterHistory.getListOfEncounters());
    }
private void populateEncounterTable(ArrayList<Encounter> encounterHistory) {
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
   
     
     DefaultTableModel model = (DefaultTableModel) tblEncounterHistory.getModel();
     model.setRowCount(0);
     for(Encounter e : encounterHistory){
         Object[] row = new Object[10];
         row[0] = e.getCounterID();
         row[1] = e.getVitalSign().getbP();

         row[2] = e.getVitalSign().getTemperature();
         row[3] = e.getVitalSign().getPulse();
         row[4] = e.getDate();

         model.addRow(row);
     }
     
 
     
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblViewName = new javax.swing.JLabel();
        lblViewssn = new javax.swing.JLabel();
        lblViewAddress = new javax.swing.JLabel();
        lblViewSex = new javax.swing.JLabel();
        lblViewPhoneNumber = new javax.swing.JLabel();
        txtViewName = new javax.swing.JTextField();
        txtViewssn = new javax.swing.JTextField();
        txtViewAddress = new javax.swing.JTextField();
        txtViewSex = new javax.swing.JTextField();
        txtViewPhoneNumber = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblViewSex1 = new javax.swing.JLabel();
        txtViewAge = new javax.swing.JTextField();
        txtViewDisease = new javax.swing.JTextField();
        lblViewPhoneNumber1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEncounterHistory = new javax.swing.JTable();

        setBackground(new java.awt.Color(143, 188, 219));

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("View or Modify Patient");

        lblViewName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblViewName.setText("Name:");

        lblViewssn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblViewssn.setText("SSN:");

        lblViewAddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblViewAddress.setText("Address:");

        lblViewSex.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblViewSex.setText("Gender:");

        lblViewPhoneNumber.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblViewPhoneNumber.setText("Phone number:");

        txtViewName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewNameActionPerformed(evt);
            }
        });

        txtViewssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewssnActionPerformed(evt);
            }
        });

        txtViewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewAddressActionPerformed(evt);
            }
        });

        txtViewPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewPhoneNumberActionPerformed(evt);
            }
        });

        btnView.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        lblViewSex1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblViewSex1.setText("Age:");

        txtViewDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtViewDiseaseActionPerformed(evt);
            }
        });

        lblViewPhoneNumber1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblViewPhoneNumber1.setText("Disease:");

        tblEncounterHistory.setBackground(new java.awt.Color(204, 255, 255));
        tblEncounterHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Encounter ID", "Blood Pressure", "Temperature", "Pulse"
            }
        ));
        jScrollPane1.setViewportView(tblEncounterHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblViewPhoneNumber)
                                    .addComponent(lblViewSex)
                                    .addComponent(lblViewAddress)
                                    .addComponent(lblViewssn)
                                    .addComponent(lblViewName)
                                    .addComponent(lblViewSex1)
                                    .addComponent(lblViewPhoneNumber1))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtViewAge, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(txtViewName, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                    .addComponent(txtViewPhoneNumber)
                                    .addComponent(txtViewSex)
                                    .addComponent(txtViewAddress)
                                    .addComponent(txtViewssn)
                                    .addComponent(txtViewDisease))
                                .addGap(18, 18, 18)
                                .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, 0)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtViewAddress, txtViewAge, txtViewName, txtViewPhoneNumber, txtViewSex, txtViewssn});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTitle)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewName)
                    .addComponent(txtViewName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewssn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewssn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewAddress)
                    .addComponent(txtViewAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewSex1)
                    .addComponent(txtViewAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewSex)
                    .addComponent(txtViewSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblViewPhoneNumber)
                    .addComponent(txtViewPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtViewDisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewPhoneNumber1))
                .addGap(9, 9, 9)
                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtViewAddress, txtViewAge, txtViewName, txtViewPhoneNumber, txtViewSex, txtViewssn});

    }// </editor-fold>//GEN-END:initComponents

    private void txtViewNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewNameActionPerformed

    private void txtViewssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewssnActionPerformed

    private void txtViewAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewAddressActionPerformed

    private void txtViewPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewPhoneNumberActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        int flag_count = 0;
        for(int i=0; i<this.listOfPatient.getListOfPatients().size(); i++) {
if(txtViewssn.getText().equals(Long.toString(this.listOfPatient.getListOfPatients().get(i).getSsn()))) {
flag_count = 1;
txtViewName.setText(this.listOfPatient.getListOfPatients().get(i).getName());
txtViewAge.setText(Integer.toString(this.listOfPatient.getListOfPatients().get(i).getAge()));
txtViewSex.setText(this.listOfPatient.getListOfPatients().get(i).getSex());
txtViewAddress.setText(this.listOfPatient.getListOfPatients().get(i).getAddress());
txtViewPhoneNumber.setText(Long.toString(this.listOfPatient.getListOfPatients().get(i).getPhoneNumber()));
txtViewDisease.setText(this.listOfPatient.getListOfPatients().get(i).getDisease());

break;
}


}
   if(flag_count == 0){
    JOptionPane.showMessageDialog(this, "Invalid SSN");
}
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int i = 0;
        int flagPoint=0;
        for(i=0; i<this.listOfPatient.getListOfPatients().size(); i++) {
        if(txtViewssn.getText().equals(Long.toString(this.listOfPatient.getListOfPatients().get(i).getSsn()))) {
            flagPoint=1;
            this.listOfPatient.getListOfPatients().remove(this.listOfPatient.getListOfPatients().get(i));
        
        }
        
         
        
    }//GEN-LAST:event_btnDeleteActionPerformed
    if(flagPoint==1){
             JOptionPane.showMessageDialog(this, "Person profile Deleted");
         }   
         else{
         JOptionPane.showMessageDialog(this, "Invalid SSN");
         }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int flagPointPointParent = 0;
int i = 0;
for(i=0; i<this.listOfPatient.getListOfPatients().size(); i++) {
if(txtViewssn.getText().equals(Long.toString(this.listOfPatient.getListOfPatients().get(i).getSsn()))) {
flagPointPointParent = 1;
break;
}
}

    String errorMsg = "SSN DOESNT EXIST";

if(flagPointPointParent == 1) {
int flagPoint = 0;
long ssn = 0;
String name = "";
int age = 0;
String sex = "";
String address = "";
long phoneNumber = 0;
String disease="";
if(Pattern.matches("^\\d{9}", txtViewssn.getText())) {
    System.out.println("check2");
ssn = Long.parseLong(txtViewssn.getText());
}
else if(txtViewssn.getText().length() == 0){
errorMsg = "SSN cannot be empty";
flagPoint = 1;
}
else {
errorMsg = "SSN should be of 9 digits";
flagPoint = 1;
}

 if(errorMsg == "SSN DOESNT EXIST" && txtViewName.getText().length() != 0) {
name = txtViewName.getText();
System.out.println("check3 " + name);
}
else if(errorMsg == "SSN DOESNT EXIST") {
flagPoint = 1;
errorMsg = "Name cannot be empty";
}

 if(errorMsg == "SSN DOESNT EXIST" && txtViewAddress.getText().length() != 0) {
address = txtViewAddress.getText();
System.out.println("check3 " + name);
}
else if(errorMsg == "SSN DOESNT EXIST") {
flagPoint = 1;
errorMsg = "Name cannot be empty";
}
 if(errorMsg == "SSN DOESNT EXIST" && Pattern.matches("^\\d{2}", txtViewAge.getText())) {
age = Integer.parseInt(txtViewAge.getText());
System.out.println(txtViewAge.getText());
}
else if(errorMsg == "SSN DOESNT EXIST") {
errorMsg = "Age should be of 2 digits";
flagPoint = 1;
}
if(errorMsg == "SSN DOESNT EXIST" && txtViewSex.getText().length() != 0) {
if(txtViewSex.getText().equals("Male") || txtViewSex.getText().equals("Female") || txtViewSex.getText().equals("Others")) {
sex = txtViewSex.getText();
System.out.println(txtViewSex.getText());
}
else if(errorMsg == "SSN DOESNT EXIST"){
errorMsg = "sex should be Male/Female/Others";
flagPoint = 1;
}
}

 if(errorMsg == "SSN DOESNT EXIST" && txtViewPhoneNumber.getText().length() != 0) {
if(Pattern.matches("^\\d{10}", txtViewPhoneNumber.getText())) {
phoneNumber = Long.parseLong(txtViewPhoneNumber.getText());
System.out.println(txtViewPhoneNumber.getText());
}
else if(errorMsg == "SSN DOESNT EXIST") {
errorMsg = "phone number  should be of 10 digits";
flagPoint = 1;
}
}
 
 if(errorMsg == "SSN DOESNT EXIST" && txtViewDisease.getText().length() != 0) {
disease = txtViewDisease.getText();
System.out.println("check3 " + name);
}
else if(errorMsg == "SSN DOESNT EXIST") {
flagPoint = 1;
errorMsg = "Name cannot be empty";
}

        
 
 if(flagPoint == 0) {
Patient newPatient;
    try {
        newPatient = new Patient(name, ssn, address, age, sex, phoneNumber,disease);
        this.listOfPatient.getListOfPatients().set(i, newPatient);
    } catch (IOException ex) {
        Logger.getLogger(PatientModifyViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ParseException ex) {
        Logger.getLogger(PatientModifyViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
    } catch (BadLocationException ex) {
        Logger.getLogger(PatientModifyViewJPanel.class.getName()).log(Level.SEVERE, null, ex);
    }

//for(int j=0; j<this.listOfHouses.size(); j++) {
//if(address.equals(this.listOfHouses.get(j).getHouseAddress())) {
//this.listOfHouses.get(j).getListOfPerson().add(newPerson);
//}
JOptionPane.showMessageDialog(this, "Person profile updated");

}
 }
 else {
  JOptionPane.showMessageDialog(this, errorMsg);
 }

    
    
    
    
    
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtViewDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtViewDiseaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtViewDiseaseActionPerformed
        
        
        
  
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblViewAddress;
    private javax.swing.JLabel lblViewName;
    private javax.swing.JLabel lblViewPhoneNumber;
    private javax.swing.JLabel lblViewPhoneNumber1;
    private javax.swing.JLabel lblViewSex;
    private javax.swing.JLabel lblViewSex1;
    private javax.swing.JLabel lblViewssn;
    private javax.swing.JTable tblEncounterHistory;
    private javax.swing.JTextField txtViewAddress;
    private javax.swing.JTextField txtViewAge;
    private javax.swing.JTextField txtViewDisease;
    private javax.swing.JTextField txtViewName;
    private javax.swing.JTextField txtViewPhoneNumber;
    private javax.swing.JTextField txtViewSex;
    private javax.swing.JTextField txtViewssn;
    // End of variables declaration//GEN-END:variables

    
}
