/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.util.ArrayList;
import java.util.regex.Pattern;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import models.City;
import models.Community;
import models.Patient;
import models.PatientDirectory;
import models.PersonDirectory;
import models.Person;

/**
 *
 * @author jacksonalexander
 */
public class PersonCreateJPanel extends javax.swing.JPanel {

    
    PersonDirectory listOfPerson;
    PatientDirectory listOfPatient;
    City city;
    Person p;
    Patient Pa;
    Community community;
    ArrayList<City> listOfCity;
    /**
     * Creates new form PersonCreate
     */

    public PersonCreateJPanel(PersonDirectory listOfPerson) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
    
this.listOfPerson = listOfPerson;
    
    }

    PersonCreateJPanel(PatientDirectory listOfPatient) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblInsertaddress1 = new javax.swing.JLabel();
        lblInsertName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtInsertaddress = new javax.swing.JTextField();
        txtInsertssn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        txtInsertName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblInsertaddress = new javax.swing.JLabel();
        lblInsertphoneNumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtInsertphoneNumber = new javax.swing.JTextField();
        txtInsertAge = new javax.swing.JTextField();
        lblInsertsex = new javax.swing.JLabel();
        lblInsertssn = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtInsertsex = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(143, 188, 219));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel3.setText("                                                    Insert Person Profile");

        lblInsertaddress1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertaddress1.setText("Age:");

        lblInsertName.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertName.setText("Name:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel7.setText("Address Should be alphanumericsals");

        txtInsertaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertaddressActionPerformed(evt);
            }
        });

        txtInsertssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertssnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel9.setText("Phone Number should be of 10 digits.");

        btnInsert.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        txtInsertName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel5.setText("SSN should be of 9 Digits");

        lblInsertaddress.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertaddress.setText("Address:");

        lblInsertphoneNumber.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertphoneNumber.setText("Phone Number:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel8.setText("Gender can be male, female or others");

        txtInsertphoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertphoneNumberActionPerformed(evt);
            }
        });

        txtInsertAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertAgeActionPerformed(evt);
            }
        });

        lblInsertsex.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertsex.setText("Gender:");

        lblInsertssn.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lblInsertssn.setText("SSN:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel4.setText("Name Should not contain numbers");

        txtInsertsex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInsertsexActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 2, 10)); // NOI18N
        jLabel6.setText("Age should be 1 0r 2 Digits");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertssn)
                    .addComponent(lblInsertaddress)
                    .addComponent(lblInsertsex)
                    .addComponent(lblInsertName)
                    .addComponent(lblInsertphoneNumber)
                    .addComponent(lblInsertaddress1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnInsert, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsertphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsertssn, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsertaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsertsex, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtInsertName, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtInsertAge, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel6))))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1280, Short.MAX_VALUE)
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtInsertAge, txtInsertName, txtInsertaddress, txtInsertphoneNumber, txtInsertsex, txtInsertssn});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtInsertName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertssn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertssn, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtInsertaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInsertaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtInsertAge, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtInsertsex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInsertsex)))
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsertphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtInsertphoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtInsertAge, txtInsertName, txtInsertaddress, txtInsertphoneNumber, txtInsertsex, txtInsertssn});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtInsertaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertaddressActionPerformed

    private void txtInsertssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertssnActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        int flag_count = 0;
        String name="";
        if(txtInsertName.getText().length()==0)
        {System.out.println("No Value Inserted");
            flag_count=1;
        } else if(Pattern.matches("[a-zA-Z]+\\.?",txtInsertName.getText()))
        {name=txtInsertName.getText();  // Prints name
        }else{System.out.println("This is an invalid Input");
            flag_count=1;
        }

        long ssn=0;
        if(Pattern.matches("^\\d{9}$", txtInsertssn.getText())){
            ssn = Long.parseLong(txtInsertssn.getText());//SSN should be 10 digits
        } else {
            System.out.println("This is an invalid Input");
            flag_count=1;
        }
       

        String address="";
        if(txtInsertaddress.getText().length()==0)
        {System.out.println("No Value Inserted");
            flag_count=1;
        } else if(Pattern.matches("[a-zA-Z]+\\.?",txtInsertaddress.getText()))
        {address=txtInsertaddress.getText();  // Prints name
        }else{System.out.println("This is an invalid Input");
            flag_count=1;
        }
        int age=0;
        if(Pattern.matches("^\\d{1,2}$", txtInsertAge.getText())){
            age = Integer.parseInt(txtInsertAge.getText());
        } else {
            System.out.println("This is an invalid Input");
            flag_count=1;
        }

        String sex="";
        if(txtInsertsex.getText().length()==0)
        {System.out.println("No Value Inserted");
            flag_count=1;
        } else if(Pattern.matches("^(?:Male|Female|Others)$",txtInsertsex.getText()))
        {sex=txtInsertsex.getText();  // Prints name
        }else{System.out.println("This is an invalid Input");
            flag_count=1;
        }

        long phoneNumber=0;
        if(Pattern.matches("^\\d{10}$", txtInsertphoneNumber.getText())){
            phoneNumber = Long.parseLong(txtInsertphoneNumber.getText());
        } else {
            System.out.println("This is an invalid Input");
            flag_count=1;
        }

        if(flag_count ==1){
            JOptionPane.showMessageDialog(this, "Invalid");
        }
        else{
            JOptionPane.showMessageDialog(this, "Person Information Saved.");
        }
        Person person = new Person(name,ssn,address, age,sex,phoneNumber);
        this.listOfPerson.addNewPerson(person);
        //        populatePersonTable(this.listOfPerson.getListOfPerson());
    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtInsertNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertNameActionPerformed

    private void txtInsertphoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertphoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertphoneNumberActionPerformed

    private void txtInsertAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertAgeActionPerformed

    private void txtInsertsexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInsertsexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInsertsexActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblInsertName;
    private javax.swing.JLabel lblInsertaddress;
    private javax.swing.JLabel lblInsertaddress1;
    private javax.swing.JLabel lblInsertphoneNumber;
    private javax.swing.JLabel lblInsertsex;
    private javax.swing.JLabel lblInsertssn;
    private javax.swing.JTextField txtInsertAge;
    private javax.swing.JTextField txtInsertName;
    private javax.swing.JTextField txtInsertaddress;
    private javax.swing.JTextField txtInsertphoneNumber;
    private javax.swing.JTextField txtInsertsex;
    private javax.swing.JTextField txtInsertssn;
    // End of variables declaration//GEN-END:variables

    private void populatePersonTable(ArrayList<Person> listOfPerson) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
